### ISSUE TITLE
refactor: use published content instead of git clone

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/create-dm-app#70]
Currently, almost the entire create-dm-app repo is uploaded to the npm registry. Since cli.js is cloning from github, it should probably be enough with package.json, readme.md and cli.js. Adding a files parameter to package.json should solve this

However, #68 may change how cli.js works, so resolve that one first

**Comment by eoaksnes** [comment]
Maybe skip all git clone stuff and only use the content that is published inside the npm package.
