### ISSUE TITLE
fix: make create-dm-app great again

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/create-dm-app#77]
https://github.com/equinor/create-dm-app

- [X] Make it build 
- [x] Make it run 
     - [x] Deploying new version of generated api in dm-core

![Image](https://github.com/equinor/create-dm-app/assets/37016135/acbbd843-5482-4210-ab92-45ab7b8be402)
Stuck on this error. Axios Request from dm-core-packages

- [x] Fix Readme @eoaksnes 
- - [ ] Step 1: Remove "cd my-app && npm start" message after running step 1
- - [x] Step 2: Specify that this could be ran as detached
- - [x] Step 3: Should be python3
- [ ] Make healthcheck pass @ingeridhellen 
- [ ] Make it easily deployable to Radix by adding dockerfile, radixconfig etc
- [ ] Make dependency to docker images be stable versions, not "latest". 
- [ ] Add requirements.txt file that contains what dm-cli version to use

**Comment by eoaksnes** [comment]
Can we move the create-dm-app to the dm-core-packages repo?
